apiVersion: v1
kind: Service
metadata:
  name: auricle
  namespace: default
spec:
  selector:
    app: auricle
  type: LoadBalancer
  ports:
  - name: auricle
    port: 80
    targetPort: 80
